name: transfer index.php to remote
on: 
#   push: 
#     branches: main
  workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout the repo
        uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
         mkdir ../build
         cp -TR . ../build
         tar -cvf deploy.tar ../build/
         
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: 18.143.66.189
          username: ubuntu
          key: ${{ secrets.KEY }}
          source: 'deploy.tar'
          target: '/home/ubuntu'
          
      - name: run commands on a remote server
        uses: fifsky/ssh-action@master
        with:
          command: |
            tar -xvf deploy.tar
            cd build
            sudo cp /home/ubuntu/build/index.php /var/www/html
          host: 18.143.66.189
          user: ubuntu
          key: ${{ secrets.KEY}}
